# Generated by Django 6.0.6 on 2026-06-30 09:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('forecast_time', models.DateTimeField(help_text='Time being predicted')),
                ('variable', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('pressure', 'Pressure'), ('rain', 'Rain')], max_length=20)),
                ('predicted_value', models.FloatField()),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('minutes_ahead', models.IntegerField(help_text='30 or 60')),
                ('model_used', models.CharField(default='ARIMA', max_length=50)),
            ],
            options={
                'ordering': ['-created_at', 'minutes_ahead'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('location', models.CharField(default='Dhaka, Bangladesh', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField(help_text='°C')),
                ('humidity', models.FloatField(help_text='%')),
                ('pressure', models.FloatField(help_text='hPa')),
                ('rain', models.FloatField(default=0.0, help_text='mm')),
                ('wind_speed', models.FloatField(default=0.0, help_text='km/h')),
                ('wind_direction', models.FloatField(default=0.0, help_text='degrees')),
                ('weather_code', models.IntegerField(default=0, help_text='WMO weather code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='weather_ai__timesta_76073b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('alert_type', models.CharField(choices=[('temperature_anomaly', 'Temperature Anomaly'), ('humidity_anomaly', 'Humidity Anomaly'), ('pressure_anomaly', 'Pressure Anomaly'), ('rain_anomaly', 'Rain Anomaly'), ('wind_anomaly', 'Wind Anomaly'), ('general_anomaly', 'General Anomaly')], default='general_anomaly', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('anomaly_score', models.FloatField(default=0.0, help_text='Isolation Forest score')),
                ('is_active', models.BooleanField(default=True)),
                ('weather_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='weather_ai.weatherreading')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
